version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mehedi
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
